import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Provider from "./Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="">
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
